### ISSUE TITLE
Prepare Telemetry Driver

### ISSUE THREAD

**Issue by MrZebulon** [EPFLRocketTeam/2024_I_AV_SW_DRIVERS#6]

**Comment by LeTiti2772005** [comment]
Dans le constructeur, quel est l'intérêt de donner une addresse à la classe radio? C'est une question d'intranet?
Ou alors est-ce que c'est le pin CS, et du coup pourquoi pas le nommer comme ça?

**Comment by MrZebulon** [comment]
@LeTiti2772005 C'est une histoire de transmission de data. La LoRa doit transmetttre sa "local address".

**Comment by LeTiti2772005** [comment]
OK alors c'est parfait. 
Mais du coup, on définit ou le CS? Je vois que tu définis le IRQ et RST mais pas le CS. Il est dans SPISettings?

Sinon le reste du code me semble pas mal, il ne manque plus que le tester ig
